[package]
name = "panel_2_profile"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.24", features = ["blocking"] }
image = "0.24.8"
anyhow = "1.0.80"
regex = "1.10.3"
